name: Spring Boot CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew test

      - name: Generate test report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Gradle Tests
          path: build/test-results/test/*.xml
          reporter: java-junit

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    #if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Get JAR file name
        id: jar
        run: |
          JAR_FILE=$(find build/libs -name "*.jar" -not -name "*-plain.jar" | head -1)
          echo "jar_file=$JAR_FILE" >> $GITHUB_OUTPUT
          echo "jar_name=$(basename $JAR_FILE)" >> $GITHUB_OUTPUT

      - name: Deploy to server
        uses: appleboy/scp-action@v0.1.8
        with:
          host: dkswoalstest.duckdns.org
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 2222
          source: ${{ steps.jar.outputs.jar_file }}
          target: "/home/${{ secrets.SERVER_USERNAME }}/app"
          strip_components: 2

      - name: Execute deployment script
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: dkswoalstest.duckdns.org
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 2222
          script: |
            cd /home/${{ secrets.SERVER_USERNAME }}/app
            
            # 기존 프로세스 종료
            pkill -f "java -jar" || true
            sleep 5
            
            # 새 애플리케이션 실행
            nohup java -jar ${{ steps.jar.outputs.jar_name }} > app.log 2>&1 &
            
            # 잠시 대기 후 프로세스 확인
            sleep 10
            if pgrep -f "java -jar" > /dev/null; then
              echo "Application started successfully"
            else
              echo "Application failed to start"
              exit 1
            fi
